# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# * https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# * https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-go-mod-patch-and-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
    ignore:
      - dependency-name: "github.com/open-policy-agent/opa"
      - dependency-name: "github.com/open-policy-agent/opa-envoy-plugin"
      - dependency-name: "github.com/envoyproxy/go-control-plane"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opa:
        patterns:
          - "github.com/open-policy-agent/opa"
          - "github.com/open-policy-agent/opa-envoy-plugin"
  - package-ecosystem: "github-actions"
    directory: "/" # For GitHub Actions, set the directory to / to check for workflow files in .github/workflows
    schedule:
      interval: "weekly"
  # Keep Docker dependencies up to date
  - package-ecosystem: "docker"
    directory: "/packaging"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/fuzz"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/.clusterfuzzlite"
    schedule:
      interval: "weekly"
