apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ingress-aws-controller
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ .Chart.Version }}
{{- if .Values.eks_iam }}
  annotations:
    eks.amazonaws.com/role-arn:
      arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.kube_ingress_aws_controller.aws_role }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-ingress-aws-controller
  labels:
    chart: {{ .Chart.Version }}
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-ingress-aws-controller
  labels:
    chart: {{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ingress-aws-controller
subjects:
- kind: ServiceAccount
  name: kube-ingress-aws-controller
  namespace: {{ .Values.namespace }}
