{{ if .Values.kube2iam.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2iam
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ .Chart.Version }}
{{- if .Values.eks_iam }}
  annotations:
    eks.amazonaws.com/role-arn:
      arn:aws:iam::AWS_ACCOUNT_ID:role/{{ .Values.kube2iam.aws_role }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube2iam
  labels:
    chart: {{ .Chart.Version }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube2iam
  labels:
    chart: {{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube2iam
subjects:
- kind: ServiceAccount
  name: kube2iam
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kube2iam-privileged-psp
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: kube2iam
  namespace: {{ .Values.namespace }}
{{ end }}
